In [1]:
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
data=pd.read_csv("Diabetes_Prediction_Dataset.csv")

In [3]:
data.shape

(5000, 13)

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Patient_ID         5000 non-null   int64
 1   Age                5000 non-null   int64
 2   Gender             5000 non-null   str
 3   BMI                4893 non-null   float64
 4   Glucose            4930 non-null   float64
 5   Blood_Pressure     5000 non-null   int64
 6   Cholesterol        5000 non-null   int64
 7   Insulin            5000 non-null   int64
 8   HbA1c              5000 non-null   float64
 9   Smoking_Status     5000 non-null   str
 10  Physical_Activity  5000 non-null   str
 11  Family_History     5000 non-null   str
 12  Diabetes           5000 non-null   str
dtypes: float64(3), int64(5), str(5)
memory usage: 611.4 KB

In [5]:
data.describe()

,Patient_ID,Age,BMI,Glucose,Blood_Pressure,Cholesterol,Insulin,HbA1c
count,5000.000000,5000.000000,4893.000000,4930.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2500.500000,48.986400,29.407398,144.456795,143.139200,221.426800,157.746200,7.988300
std,1443.520003,18.173813,7.254359,43.887777,87.414816,57.436379,82.357275,2.017408
min,1.000000,18.000000,17.000000,70.000000,90.000000,120.000000,15.000000,4.500000
25%,1250.750000,33.000000,23.100000,106.000000,112.000000,172.000000,86.000000,6.200000
50%,2500.500000,49.000000,29.400000,144.000000,136.000000,222.000000,158.000000,7.900000
75%,3750.250000,65.000000,35.800000,182.000000,158.000000,271.000000,229.000000,9.800000
max,5000.000000,80.000000,42.000000,220.000000,999.000000,320.000000,300.000000,11.500000

In [6]:
data.isnull().sum()

Patient_ID             0
Age                    0
Gender                 0
BMI                  107
Glucose               70
Blood_Pressure         0
Cholesterol            0
Insulin                0
HbA1c                  0
Smoking_Status         0
Physical_Activity      0
Family_History         0
Diabetes               0
dtype: int64

In [7]:
data["BMI"] = data["BMI"].fillna(data["BMI"].median())
data["Glucose"] = data["Glucose"].fillna(data["Glucose"].median())

In [8]:
data.isnull().sum()

Patient_ID           0
Age                  0
Gender               0
BMI                  0
Glucose              0
Blood_Pressure       0
Cholesterol          0
Insulin              0
HbA1c                0
Smoking_Status       0
Physical_Activity    0
Family_History       0
Diabetes             0
dtype: int64

In [9]:
print(data["Gender"].unique())
print(data["Smoking_Status"].unique())
print(data["Physical_Activity"].unique())
print(data["Family_History"].unique())

<ArrowStringArray>
['Male', 'Female', 'Unknown']
Length: 3, dtype: str
<ArrowStringArray>
['Current', 'Never', 'Former']
Length: 3, dtype: str
<ArrowStringArray>
['High', 'Low', 'Moderate']
Length: 3, dtype: str
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

In [10]:
print((data["Gender"] == "Unknown").sum())

46

In [11]:
data = data[data["Gender"] != "Unknown"]

In [12]:
print(data["Gender"].unique())

<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

In [13]:
data.head()

,Patient_ID,Age,Gender,BMI,Glucose,Blood_Pressure,Cholesterol,Insulin,HbA1c,Smoking_Status,Physical_Activity,Family_History,Diabetes
0,1,58,Male,17.6,140.0,121,177,86,9.7,Current,High,Yes,Yes
1,2,56,Male,31.0,209.0,143,176,244,8.6,Never,Low,No,Yes
2,3,23,Female,19.4,158.0,167,187,37,9.6,Current,Low,No,No
3,4,41,Male,34.6,81.0,174,178,163,11.4,Never,Low,No,No
4,5,31,Female,34.5,88.0,167,282,102,8.2,Never,Low,No,No

In [14]:
data.describe()

,Patient_ID,Age,BMI,Glucose,Blood_Pressure,Cholesterol,Insulin,HbA1c
count,4954.000000,4954.000000,4954.000000,4954.000000,4954.000000,4954.000000,4954.000000,4954.000000
mean,2501.600525,48.962858,29.405067,144.445095,143.121518,221.360920,157.792693,7.986536
std,1442.647043,18.186103,7.166727,43.582452,86.934119,57.465299,82.341400,2.017165
min,1.000000,18.000000,17.000000,70.000000,90.000000,120.000000,15.000000,4.500000
25%,1250.250000,33.000000,23.200000,107.000000,112.000000,172.000000,87.000000,6.200000
50%,2504.500000,49.000000,29.400000,144.000000,136.000000,222.000000,158.000000,7.900000
75%,3749.750000,65.000000,35.600000,182.000000,159.000000,271.000000,229.000000,9.775000
max,5000.000000,80.000000,42.000000,220.000000,999.000000,320.000000,300.000000,11.500000

In [15]:
# Find unrealistic values
print(data[data["Blood_Pressure"] > 250])

      Patient_ID  Age  Gender   BMI  Glucose  Blood_Pressure  Cholesterol  \
36            37   22  Female  27.2    208.0             999          226
67            68   29    Male  21.4    167.0             999          294
226          227   54    Male  31.1    118.0             999          258
286          287   52  Female  19.3    126.0             999          289
290          291   29  Female  31.0    217.0             999          186
355          356   72  Female  27.3    180.0             999          275
424          425   54  Female  36.4     74.0             999          158
432          433   62  Female  30.8    182.0             999          268
556          557   39  Female  29.4    185.0             999          182
585          586   30  Female  36.3    176.0             999          232
705          706   28    Male  25.7    177.0             999          241
741          742   62  Female  26.8     95.0             999          307
836          837   50    Male  35.2     91.0             999          233
867          868   60  Female  29.6    206.0             999          177
906          907   37    Male  42.0     91.0             999          284
1042        1043   48  Female  40.3    187.0             999          207
1100        1101   37  Female  19.5    173.0             999          199
1264        1265   74  Female  36.6    117.0             999          206
1392        1393   30    Male  20.3    109.0             999          179
1422        1423   44    Male  29.6     99.0             999          258
1496        1497   66    Male  17.0     75.0             999          260
1559        1560   53  Female  34.4    123.0             999          169
1696        1697   52    Male  20.9    215.0             999          258
2043        2044   23  Female  25.4    109.0             999          154
2380        2381   69    Male  37.1    188.0             999          161
2421        2422   39  Female  20.7    186.0             999          133
2458        2459   77    Male  18.3    217.0             999          147
2683        2684   44  Female  22.2    160.0             999          236
2741        2742   23  Female  28.4    151.0             999          185
3088        3089   45    Male  32.5    173.0             999          295
3193        3194   55  Female  17.1    200.0             999          197
3357        3358   38    Male  32.8    197.0             999          201
3430        3431   65  Female  17.5    168.0             999          173
3624        3625   73    Male  29.4    166.0             999          120
3659        3660   29  Female  27.8    193.0             999          276
3670        3671   35    Male  33.9    136.0             999          265
3672        3673   48    Male  31.2    199.0             999          267
3733        3734   54    Male  37.8    107.0             999          190
3821        3822   48    Male  30.5    187.0             999          160
3968        3969   61    Male  17.1    178.0             999          154
4130        4131   48    Male  32.8     88.0             999          310
4355        4356   29  Female  17.2    220.0             999          218
4391        4392   47  Female  18.6    127.0             999          162
4464        4465   53  Female  27.4    182.0             999          259
4616        4617   71    Male  19.7    140.0             999          307
4702        4703   47  Female  21.3    190.0             999          169

      Insulin  HbA1c Smoking_Status Physical_Activity Family_History Diabetes
36         46    5.9         Former          Moderate            Yes       No
67        138    8.0        Current               Low            Yes      Yes
226       173    5.7          Never               Low            Yes      Yes
286       184    6.8         Former               Low             No       No
290       223    7.2        Current          Moderate             No      Yes
355       138    8.4          Never          Moderate             No      Yes
424        15   11.0        Current          Moderate             No      Yes
432        35    5.4        Current              High             No      Yes
556       179    6.9         Former              High             No      Yes
585       245   10.5          Never          Moderate            Yes      Yes
705       289    9.3          Never              High             No       No
741       152    8.0          Never               Low             No       No
836        37    6.4          Never              High             No       No
867       221    8.0         Former          Moderate             No      Yes
906       214   10.6          Never          Moderate             No       No
1042       89    6.3          Never          Moderate            Yes      Yes
1100      230    5.2         Former          Moderate            Yes       No
1264      163    4.9         Former              High             No       No
1392       19    5.5          Never          Moderate             No       No
1422      221    5.7         Former               Low            Yes       No
1496      280    7.1         Former              High             No       No
1559      140    5.8          Never          Moderate            Yes      Yes
1696      282    9.0        Current               Low            Yes      Yes
2043      220    7.9         Former              High             No       No
2380       28    5.3        Current              High             No      Yes
2421      138    7.3         Former              High            Yes      Yes
2458      215    5.8          Never               Low             No       No
2683      206    7.2        Current          Moderate            Yes      Yes
2741       48    5.7        Current              High            Yes       No
3088      207   10.1          Never              High             No      Yes
3193      124    7.9          Never              High            Yes      Yes
3357      193    6.0        Current               Low             No       No
3430      168    7.0          Never              High             No      Yes
3624      284   10.9          Never          Moderate            Yes      Yes
3659      232   10.0          Never              High            Yes      Yes
3670      238    8.1        Current               Low             No       No
3672      127    8.4          Never              High             No      Yes
3733      175    5.4         Former              High             No       No
3821      239    8.4         Former          Moderate             No      Yes
3968       41   10.5        Current               Low            Yes      Yes
4130      234    4.7         Former               Low            Yes      Yes
4355       57    4.8          Never               Low            Yes       No
4391      284    6.7         Former               Low            Yes      Yes
4464       94    5.7          Never              High             No       No
4616       73   10.2        Current          Moderate            Yes      Yes
4702      243   11.4         Former               Low            Yes      Yes

In [16]:
# Replace them with the median
data.loc[data["Blood_Pressure"] > 250, "Blood_Pressure"] = data["Blood_Pressure"].median()

In [17]:
data.describe()

,Patient_ID,Age,BMI,Glucose,Blood_Pressure,Cholesterol,Insulin,HbA1c
count,4954.000000,4954.000000,4954.000000,4954.000000,4954.000000,4954.000000,4954.000000,4954.000000
mean,2501.600525,48.962858,29.405067,144.445095,135.108195,221.360920,157.792693,7.986536
std,1442.647043,18.186103,7.166727,43.582452,26.278855,57.465299,82.341400,2.017165
min,1.000000,18.000000,17.000000,70.000000,90.000000,120.000000,15.000000,4.500000
25%,1250.250000,33.000000,23.200000,107.000000,112.000000,172.000000,87.000000,6.200000
50%,2504.500000,49.000000,29.400000,144.000000,136.000000,222.000000,158.000000,7.900000
75%,3749.750000,65.000000,35.600000,182.000000,158.000000,271.000000,229.000000,9.775000
max,5000.000000,80.000000,42.000000,220.000000,180.000000,320.000000,300.000000,11.500000

In [18]:
#Count duplicate rows-
print(data.duplicated().sum())

0

In [19]:
print(data[data.duplicated()])

Empty DataFrame
Columns: [Patient_ID, Age, Gender, BMI, Glucose, Blood_Pressure, Cholesterol, Insulin, HbA1c, Smoking_Status, Physical_Activity, Family_History, Diabetes]
Index: []

In [20]:
data=data.drop_duplicates()

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
le = LabelEncoder()

In [23]:
data["Gender"] = le.fit_transform(data["Gender"])

data["Smoking_Status"] = le.fit_transform(data["Smoking_Status"])

data["Physical_Activity"] = le.fit_transform(data["Physical_Activity"])

data["Family_History"] = le.fit_transform(data["Family_History"])

data["Diabetes"] = le.fit_transform(data["Diabetes"])

In [24]:
data.head()

,Patient_ID,Age,Gender,BMI,Glucose,Blood_Pressure,Cholesterol,Insulin,HbA1c,Smoking_Status,Physical_Activity,Family_History,Diabetes
0,1,58,1,17.6,140.0,121,177,86,9.7,0,0,1,1
1,2,56,1,31.0,209.0,143,176,244,8.6,2,1,0,1
2,3,23,0,19.4,158.0,167,187,37,9.6,0,1,0,0
3,4,41,1,34.6,81.0,174,178,163,11.4,2,1,0,0
4,5,31,0,34.5,88.0,167,282,102,8.2,2,1,0,0

In [25]:
print(data.dtypes)

Patient_ID             int64
Age                    int64
Gender                 int64
BMI                  float64
Glucose              float64
Blood_Pressure         int64
Cholesterol            int64
Insulin                int64
HbA1c                float64
Smoking_Status         int64
Physical_Activity      int64
Family_History         int64
Diabetes               int64
dtype: object

In [26]:
data = data.drop("Patient_ID", axis=1)

In [27]:
# Features (Input)
X = data.drop("Diabetes", axis=1)

# Target (Output)
y = data["Diabetes"]

In [28]:
X.head()

,Age,Gender,BMI,Glucose,Blood_Pressure,Cholesterol,Insulin,HbA1c,Smoking_Status,Physical_Activity,Family_History
0,58,1,17.6,140.0,121,177,86,9.7,0,0,1
1,56,1,31.0,209.0,143,176,244,8.6,2,1,0
2,23,0,19.4,158.0,167,187,37,9.6,0,1,0
3,41,1,34.6,81.0,174,178,163,11.4,2,1,0
4,31,0,34.5,88.0,167,282,102,8.2,2,1,0

In [29]:
y.head()

0    1
1    1
2    0
3    0
4    0
Name: Diabetes, dtype: int64

In [30]:
X.shape

(4954, 11)

In [31]:
y.shape

(4954,)

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [34]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
model = DecisionTreeClassifier(random_state=42)

In [36]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [37]:
y_pred = model.predict(X_test)

In [38]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.9848637739656912

In [39]:
from sklearn.metrics import precision_score

print("Precision:", precision_score(y_test, y_pred))

Precision: 0.9833610648918469

In [40]:
from sklearn.metrics import recall_score

print("Recall:", recall_score(y_test, y_pred))

Recall: 0.9916107382550335

In [41]:
from sklearn.metrics import f1_score

print("F1 Score:", f1_score(y_test, y_pred))

F1 Score: 0.9874686716791979

In [42]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[385  10]
 [  5 591]]

In [43]:
import joblib

joblib.dump(model, "model.pkl")

['model.pkl']

In [44]:
model = joblib.load("model.pkl")